sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile -t eelzinaty/docker-react .

script:
  - docker run eelzinaty/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-ci"
  env: "DockerCi-env"
  bucket_name: "elasticbeanstalk-us-west-2-050124817506"
  bucket_path: "docker-ci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"